# Generated by Django 4.0.6 on 2022-11-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
