# Generated by Django 4.0.4 on 2022-11-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_presence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presence',
        ),
    ]
