# Generated by Django 4.0.6 on 2022-11-27 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_dept_cover_alter_department_dept_title'),
        ('course', '0008_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_upload',
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
