# Generated by Django 4.0.6 on 2022-11-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_course_date_upload_course_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_upload',
            field=models.DateTimeField(auto_now=True, verbose_name='date upload'),
        ),
    ]
