# Generated by Django 4.0.6 on 2022-11-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='pdp',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile'),
        ),
    ]
