# Generated by Django 4.0.6 on 2022-11-28 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_dept_cover_alter_department_dept_title'),
        ('accounts', '0002_myuser_pdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='dept',
            field=models.ManyToManyField(to='department.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='department'),
        ),
    ]
