# Generated by Django 4.0.6 on 2022-11-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_dept_alter_student_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='dept',
        ),
    ]
