# Generated by Django 4.0.6 on 2022-11-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_teacher_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='visa',
            field=models.IntegerField(default=0),
        ),
    ]
