# Generated by Django 4.1.7 on 2023-08-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_institut_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='institut',
            name='categorie',
            field=models.CharField(blank=True, choices=[('EB', 'Economics and Business Sciences'), ('HS', 'Health Sciences'), ('ES', 'Engineering Sciences')], max_length=2),
        ),
    ]
