# Generated by Django 4.1.7 on 2023-08-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_institut_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institut',
            name='image',
            field=models.ImageField(blank=True, upload_to='media\\logo_institut'),
        ),
        migrations.AlterField(
            model_name='institut',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
