# Generated by Django 3.2.4 on 2023-09-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_institut_image_alter_institut_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institut',
            name='categorie',
        ),
        migrations.AlterField(
            model_name='institut',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='institut',
            name='name',
            field=models.TextField(),
        ),
    ]
