# Generated by Django 3.2.4 on 2023-09-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_course_teacher'),
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastnotification',
            name='message',
        ),
        migrations.AddField(
            model_name='broadcastnotification',
            name='course',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='broadcast_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
