# Generated by Django 4.0.6 on 2022-11-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_cover',
            field=models.ImageField(blank=True, null=True, upload_to='department/cover'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_title',
            field=models.CharField(max_length=100, verbose_name='department'),
        ),
    ]
